server:
  port: 8887

github:
  client:
    id: f01d814b8e478cff6471
    secret: ee697d6a64183ce1c4b1117d2105504c32d5df19
  redirect:
    uri: http://localhost:8887/callback
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/community?characterEncoding=utf8&useSSL=false
    username: root
    password: root
mybatis:
  configuration:
    map-underscore-to-camel-case: true